///////////////////////////////////////////////////////////
//  BasicModel.cs
//  Implementation of the Class BasicModel
//  Generated by Enterprise Architect
//  Created on:      04-ноя-2014 12:01:08
//  Original author: Samurai
///////////////////////////////////////////////////////////




public class BasicModel : Object, Object {

	private int Alive = 0;
	private int BalisticSkill;
	private int Initiative;
	private int InvulnerableSave = 7;
	private int Move = 6;
	private int Stilness = 0;
	private int Strength;
	private Weapon[] Wapons;
	private int WeaponSkill;
	private int Wound;

	public BasicModel(){

	}

	~BasicModel(){

	}

	public override void Dispose(){

	}

	public abstract void Charge();

	public void Paint(){

	}

	public abstract Wound Shot();

	public Point3D VisiblePoints(){

		return null;
	}

}//end BasicModel