///////////////////////////////////////////////////////////
//  DiceGenerator.cs
//  Implementation of the Class DiceGenerator
//  Generated by Enterprise Architect
//  Created on:      04-ноя-2014 12:03:33
//  Original author: User
///////////////////////////////////////////////////////////




public class DiceGenerator {

	public DiceGenerator(){

	}

	~DiceGenerator(){

	}

	public virtual void Dispose(){

	}

	public int D2(){

		return 0;
	}

	public int D3(){

		return 0;
	}

	public int D6(){

		return 0;
	}

	public int D66(){

		return 0;
	}

}//end DiceGenerator