///////////////////////////////////////////////////////////
//  Dice.java
//  Implementation of the Class Dice
//  Generated by Enterprise Architect
//  Created on:      04-ноя-2014 12:04:29
//  Original author: User
///////////////////////////////////////////////////////////




public class Dice {

	public int Dicce;

	public Dice(){

	}

	~Dice(){

	}

	public virtual void Dispose(){

	}

}//end Dice