///////////////////////////////////////////////////////////
//  Effect.cs
//  Implementation of the Class Effect
//  Generated by Enterprise Architect
//  Created on:      04-ноя-2014 12:01:06
//  Original author: Samurai
///////////////////////////////////////////////////////////




public class Effect {

	private int Type;

	public Effect(){

	}

	~Effect(){

	}

	public virtual void Dispose(){

	}

}//end Effect