///////////////////////////////////////////////////////////
//  Exepshons.cs
//  Implementation of the Class Exepshons
//  Generated by Enterprise Architect
//  Created on:      04-ноя-2014 12:03:32
//  Original author: User
///////////////////////////////////////////////////////////




public class Exepshons {

	public Exepshons(){

	}

	~Exepshons(){

	}

	public virtual void Dispose(){

	}

	/// 
	/// <param name="DiceRolls"></param>
	/// <param name="DiceRollMassive"></param>
	/// <param name="Reroll"></param>
	/// <param name="RerollMassive"></param>
	/// <param name="ColmandReroll"></param>
	/// <param name="AmountComandReroll"></param>
	public int DiceRoll(int DiceRolls, int[] DiceRollMassive, int Reroll, int[] RerollMassive, int ColmandReroll, int AmountComandReroll){

		return 0;
	}

}//end Exepshons