///////////////////////////////////////////////////////////
//  Game.cs
//  Implementation of the Class Game
//  Generated by Enterprise Architect
//  Created on:      04-ноя-2014 12:03:36
//  Original author: User
///////////////////////////////////////////////////////////




public class Game {

	private int NowPlayer;
	private int phase;
	private Player[2] Players;
	private int Turn;

	public Game(){

	}

	~Game(){

	}

	public virtual void Dispose(){

	}

	/// 
	/// <param name="Target"></param>
	/// <param name="WeaponTyper"></param>
	/// <param name="Sourse"></param>
	public int Shooting(Unit Target, int WeaponTyper, Unit Sourse){

		return 0;
	}

	/// 
	/// <param name="Target"></param>
	/// <param name="Shots"></param>
	/// <param name="HowManyShot"></param>
	public void Wounding(Unit Target, Wound[] Shots, int HowManyShot){

	}

}//end Game