///////////////////////////////////////////////////////////
//  Infantry.cs
//  Implementation of the Class Infantry
//  Generated by Enterprise Architect
//  Created on:      04-ноя-2014 12:01:10
//  Original author: Samurai
///////////////////////////////////////////////////////////




public class Infantry : BasicModel {

	private int ArmorSave = 7;
	private int Leadership;
	private int Toughnes;

	public Infantry(){

	}

	~Infantry(){

	}

	public override void Dispose(){

	}

}//end Infantry