///////////////////////////////////////////////////////////
//  MapInterfeise.cs
//  Implementation of the Class MapInterfeise
//  Generated by Enterprise Architect
//  Created on:      04-ноя-2014 12:03:37
//  Original author: User
///////////////////////////////////////////////////////////




public class MapInterfeise {

	public MapInterfeise(){

	}

	~MapInterfeise(){

	}

	public virtual void Dispose(){

	}

}//end MapInterfeise