///////////////////////////////////////////////////////////
//  MiniMap.cs
//  Implementation of the Class MiniMap
//  Generated by Enterprise Architect
//  Created on:      04-ноя-2014 12:03:38
//  Original author: Samurai
///////////////////////////////////////////////////////////




public class MiniMap {

	public MiniMap(){

	}

	~MiniMap(){

	}

	public virtual void Dispose(){

	}

}//end MiniMap