///////////////////////////////////////////////////////////
//  Player.cs
//  Implementation of the Class Player
//  Generated by Enterprise Architect
//  Created on:      04-ноя-2014 14:59:26
//  Original author: Samurai
///////////////////////////////////////////////////////////




public class Player {

	private Unit[] PlayersUnit;
	public Unit m_Unit;

	public Player(){

	}

	~Player(){

	}

	public virtual void Dispose(){

	}

}//end Player