///////////////////////////////////////////////////////////
//  Point.cs
//  Implementation of the Class Point
//  Generated by Enterprise Architect
//  Created on:      04-ноя-2014 12:01:11
//  Original author: Samurai
///////////////////////////////////////////////////////////




public class Point {

	private int x;
	private int y;

	public Point(){

	}

	~Point(){

	}

	public virtual void Dispose(){

	}

}//end Point