///////////////////////////////////////////////////////////
//  Point3D.java
//  Implementation of the Class Point3D
//  Generated by Enterprise Architect
//  Created on:      04-ноя-2014 12:04:28
//  Original author: User
///////////////////////////////////////////////////////////




public class Point3D {

	private Point3D Next = NULL;
	private int x;
	private int y;
	private int z;

	public Point3D(){

	}

	~Point3D(){

	}

	public virtual void Dispose(){

	}

	public Point3D GetNext(){

		return null;
	}

}//end Point3D