///////////////////////////////////////////////////////////
//  Unit.cs
//  Implementation of the Class Unit
//  Generated by Enterprise Architect
//  Created on:      04-ноя-2014 12:01:12
//  Original author: Samurai
///////////////////////////////////////////////////////////




public class Unit {

	private int Alive = 0;
	private Effect[] Effects;
	private BasicModel[] Units;
	public BasicModel m_BasicModel;
	public Effect m_Effect;

	public Unit(){

	}

	~Unit(){

	}

	public virtual void Dispose(){

	}

}//end Unit