///////////////////////////////////////////////////////////
//  Weapon.cs
//  Implementation of the Class Weapon
//  Generated by Enterprise Architect
//  Created on:      04-ноя-2014 12:01:13
//  Original author: Samurai
///////////////////////////////////////////////////////////




public class Weapon {

	private int ArmorPenetretion = 7;
	private int Strenght;
	private int StrenghtModification*;
	private int StrenghtModification+;
	public BasicModel m_BasicModel;

	public Weapon(){

	}

	~Weapon(){

	}

	public virtual void Dispose(){

	}

}//end Weapon