///////////////////////////////////////////////////////////
//  Wound.cs
//  Implementation of the Class Wound
//  Generated by Enterprise Architect
//  Created on:      04-ноя-2014 12:01:14
//  Original author: Samurai
///////////////////////////////////////////////////////////




public class Wound {

	private int ap = 7;
	private Effect[] Efects;
	private int HowMany;
	private Wound NextWound = NULL;
	private int s;
	private int Strenght;

	public Wound(){

	}

	~Wound(){

	}

	public virtual void Dispose(){

	}

}//end Wound