///////////////////////////////////////////////////////////
//  BasicModel.cs
//  Implementation of the Class BasicModel
//  Generated by Enterprise Architect
//  Created on:      04-ноя-2014 12:01:08
//  Original author: Samurai
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using System.Windows.Forms;

public abstract class BasicModel {

	protected int Alive = 0;
	protected int BalisticSkill;
	protected int Initiative;
	protected int InvulnerableSave = 7;
	protected int Move = 6;
	protected int Stilness = 0;
	protected int Strength;
    protected int Moved=0;
	protected Weapon[] Weapons;
    protected Weapon m_Weapons;
    public Unit w_Unit;
	protected int WeaponSkill;
	protected int Wound;
    protected int x, y;


	public BasicModel()
    {
	}

    public virtual List<Wound> Shoot(int t)
    {
        List<Wound> L = new List<Wound> {};
        List<int> dice;
        L.AddRange(Weapons[0].Shoot(Moved));
        int n = L.Capacity;
        dice = new DiceGenerator().manyD6(n);
        TextBox Box = new TextBox();
        MessageBox.Show("");
        return L;
    }

	~BasicModel()
    {

	}

    public abstract void Paint();

}//end BasicModel