///////////////////////////////////////////////////////////
//  DiceGenerator.cs
//  Implementation of the Class DiceGenerator
//  Generated by Enterprise Architect
//  Created on:      04-ноя-2014 12:03:33
//  Original author: User
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using System;


public class DiceGenerator
{       
    Random r=new Random();

    public int rand(int a,int b)
    {
        return (r.Next() % (b - a + 1 )) + a;
    }

	public DiceGenerator(){

	}

	~DiceGenerator(){

	}

	public virtual void Dispose(){

	}

	public int D2(){

		return 0;
	}

	public int D3(){

		return 0;
	}

	public int D6()
    {

        return r.Next()%6+1;
	}

    public List<int> manyD6(int m)
    {
        List<int> L = new List<int> { };
        for(int i=0;i<m;i++)
        {
            L.Add(D6());
        }
        return L;
    }

	public int D66(){

		return 0;
	}

}//end DiceGenerator