///////////////////////////////////////////////////////////
//  Infantry.cs
//  Implementation of the Class Infantry
//  Generated by Enterprise Architect
//  Created on:      04-ноя-2014 12:01:10
//  Original author: Samurai
///////////////////////////////////////////////////////////




public class Infantry : BasicModel {

	private int ArmorSave = 7;
	private int Leadership;
	private int Toughnes;

	public Infantry()
    {
        BalisticSkill = 3;
        WeaponSkill = 3;
        Strength = 3;
        Toughnes = 3;
        ArmorSave = 2;
        Weapons = new Weapon[1];
        Weapons[0] = new Weapon();
        m_Weapons = Weapons[0];
        foreach(Weapon w in Weapons)
        {
            w.w_BasicModel = this;
        }
	}
	~Infantry(){

	}

	public override void Paint()
    {

	}

}//end Infantry