///////////////////////////////////////////////////////////
//  Map.cs
//  Implementation of the Class Map
//  Generated by Enterprise Architect
//  Created on:      04-ноя-2014 12:01:15
//  Original author: Samurai
///////////////////////////////////////////////////////////




public class Map {

	private Unit[] AllUnits;
	private Point Coord;
	private Object MapObjects;

	public Map(){

	}

	~Map(){

	}

	public virtual void Dispose(){

	}

	/// 
	/// <param name="Click"></param>
	public BasicModel MouseClick(Point Click){

		return null;
	}

	public void Paint(){

	}

}//end Map