///////////////////////////////////////////////////////////
//  Weapon.cs
//  Implementation of the Class Weapon
//  Generated by Enterprise Architect
//  Created on:      04-ноя-2014 12:01:13
//  Original author: Samurai
///////////////////////////////////////////////////////////



using System.Collections.Generic;

enum TypeWeapon
{
    Heavy,
    Assault
}


public class Weapon {

	private int ArmorPenetretion = 7;
	private int Strenght;
    private TypeWeapon Type;
    private int Shoots;
	private int StrenghtModificationMute;
	private int StrenghtModificationPlus;
	public BasicModel w_BasicModel;

	public Weapon()
    {
        Strenght = 4;
        Type = TypeWeapon.Assault;
        Shoots = 2;
	}

    public virtual List<Wound> Shoot(int moved,int bs)
    {
        List<Wound> L = new List<Wound> { };
        for (int i=0; i<Shoots;i++ )
        {
            L.Add(new Wound(Strenght, ArmorPenetretion, new Effect[0],bs,w_BasicModel));
        }
        return L;
    }

	~Weapon()
    {

	}

	public virtual void Dispose(){

	}

}//end Weapon