///////////////////////////////////////////////////////////
//  Wound.cs
//  Implementation of the Class Wound
//  Generated by Enterprise Architect
//  Created on:      04-ноя-2014 12:01:14
//  Original author: Samurai
///////////////////////////////////////////////////////////




public class Wound {

	private int ap = 7;
	private Effect[] Efects;
    private Effect m_Effect;
	private int Strenght;

	public Wound(int S,int AP,Effect[] Ef)
    {
        ap = AP;
        Strenght=S;
        Efects=Ef;
	}

	~Wound(){

	}
}//end Wound